# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: xterm-256color
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
#TERM: alacritty

window:
  padding:
    x: 5
    y: 5

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Window decorations
  decorations: full

  # Startup Mode (changes require restart)
  startup_mode: Windowed
  # Window title
  #title: Alacritty

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 50000

  # Scrolling distance multiplier.
  multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: "DroidSansMono Nerd Font"
    # style: Thin

  # Point size
  size: 13.0
  # Offset is the extra space around each character. `offset.y` can be thought
  # of as modifying the line spacing, and `offset.x` as modifying the letter
  # spacing.
  offset:
    x: 0
    y: 0
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the
  # right, increasing `y` moves the glyph upward.
  glyph_offset:
    x: 0
    y: 0
  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`.
  use_thin_strokes: true

# Colors (Tomorrow Night)
colors:
  # Default colors
  primary:
    background: "0x192330"
    foreground: "0xcdcecf"

  # Normal colors
  normal:
    black: "0x3b4252"
    red: "0xbf616a"
    green: "0xa3be8c"
    yellow: "0xebcb8b"
    blue: "0x81a1c1"
    magenta: "0xb48ead"
    cyan: "0x88c0d0"
    white: "0xe5e9f0"
  # Bright colors
  bright:
    black: "0x465780"
    red: "0xd06f79"
    green: "0xb1d196"
    yellow: "0xf0d399"
    blue: "0x8cafd2"
    magenta: "0xc895bf"
    cyan: "0x93ccdc"
    white: "0xe7ecf4"
  indexed_colors:
    - { index: 16, color: "0xc9826b" }
    - { index: 17, color: "0xbf88bc" }

# Live config reload (changes require restart)
live_config_reload: true

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g.
# `/bin/fish`. Entries in `shell.args` are passed unmodified as arguments to the
# shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux/BSD) user login shell
#   - (Windows) powershell
shell:
  program: ubuntu

# Startup directory
#
# Directory the shell is started in. If this is unset, or `None`, the working
# directory of the parent process will be used.
working_directory: None

# Send ESC (\x1b) before characters when alt is pressed.
#alt_send_esc: true

# Offer IPC using `alacritty msg` (unix only)
#ipc_socket: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: false
# Regex hints

# Key bindings
#
# If the same trigger is assigned to multiple actions, all of them are executed
# in the order they were defined in.
key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
#debug:
# Display the time it takes to redraw each frame.
#render_timer: false

# Keep the log file after quitting Alacritty.
#persistent_logging: false

# Log level
#
# Values for `log_level`:
#   - Off
#   - Error
#   - Warn
#   - Info
#   - Debug
#   - Trace
#log_level: Warn

# Print all received window events.
#print_events: false

# Highlight window damage information.
#highlight_damage: false
